spring:
  profiles: 
    active: dev
  datasource:
    initialize: false

#端口号
server:
  port: 8080

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#日志配置
logging:
  config: classpath:log4j2.yml
