spring:
  profiles: 
    active: dev
  datasource:
    initialize: false

server:
  port: 8080

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
